### ISSUE TITLE
Gradio3.39，Display error issues，GradioDeprecationWarning

### ISSUE THREAD

**Issue by wzgrx** [kohya-ss/sd-webui-additional-networks#222]
res = original_IOComponent_init(self, *args, **kwargs)
G:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\metadata_editor.py:399: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
G:\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\metadata_editor.py:521: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  cover_image = gr.Image(

**Comment by illuculent** [comment]
Still no fix for this? It is now Sept 23 and this was addressed to be an issue on Aug 5. Get this error every load.

**Comment by ENTPRESTIGIOUS** [comment]
I have the same issue.

**Comment by YaHaHa10** [comment]
I have the same issue.
![Uploading webui-user_start_error_additional-networks.png…]()

**Comment by YaHaHa10** [comment]
I still have the error. 
Pls help, many thanks.
![webui-user_start_error_additional-networks](https://github.com/kohya-ss/sd-webui-additional-networks/assets/125726578/b04540e5-ac9d-4bad-9027-9066bb7d3429)
